### ISSUE TITLE
if(tpfittime > 1495040000) { break; }

### ISSUE THREAD

**Issue by alexandertuna** [crogan/MMFE8_DataFormats#27]
@jrfarah 

https://github.com/crogan/MMFE8_DataFormats/blob/master/src/combineTPGBT.C#L308

lol

**Comment by jrfarah** [comment]
@alexandertuna Hey Alex! I'll have the time break removed in a few minutes. Thanks for the notice!

**Comment by jrfarah** [comment]
@alexandertuna  pull request opened.

**Comment by alexandertuna** [comment]
https://github.com/crogan/MMFE8_DataFormats/pull/28
