### ISSUE TITLE
Rename cloned tree 

### ISSUE THREAD

**Issue by alexandertuna** [crogan/MMFE8_DataFormats#29]
@jrfarah 

Minor request: could you rename the cloned tree to inform the downstream stuff that it's looking at a combined TP root file? Specifically, [this](https://github.com/crogan/MMFE8_DataFormats/blob/master/python/combineTPMM.py#L41) expects it. 

Could you add:

`combdata->SetName("TPcomb_data");`

after cloning?

**Comment by alexandertuna** [comment]
No rush -- you can wait for Ann to accept the other PR.

**Comment by jrfarah** [comment]
@alexandertuna no worries, i can add it right now, and it should be added to the currently open pull request.

**Comment by alexandertuna** [comment]
Closing this because Joe fixed it and I didn't realize.

https://github.com/crogan/MMFE8_DataFormats/pull/28
